### ISSUE TITLE
Crash at exit

### ISSUE THREAD

**Issue by chcg** [StanDog/npp-zoomdisabler#3]
See https://notepad-plus-plus.org/community/topic/15643/notepad-crashes-at-exit/9. Seems v1.2 is causing problems.

**Comment by StanDog** [comment]
Thank you for reporting this issue. Unfortunately, I can't reproduce the error. I tested the plugin with the 32-bit and 64-bit version on Windows 7 and Windows 10 without any problems. Maybe it is a specific setup combination or another plugin has a problem with the Zoom Disabler plugin. Could you please post your combination, if you have the problem too? I'll try patrickdrd's setup.

**Comment by chcg** [comment]
Just want to report it. I have not tried to reproduce it.

**Comment by BasilTomato** [comment]
Same problem happens to me every time I try to close n++: "A problem caused the program to stop working correctly. Please close the program."

Debug info:

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1937
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by RobertOnGit** [comment]
Notepad++ v8.4.8 x64 with eight plug-ins installed:
I have the same crash on Windows Server 2016/2019, not on Windows 10/11.
After removing all plug-ins and adding them back in one-by-one I found that _Zoom Disabler 1.2_ is causing this same error.
Note that the event log doesn't point explicitly to the plug-in, just to Windows _combase.dll_.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4427. The root cause seems to be the combination with DSpell plugin. Created https://github.com/Predelnik/DSpellCheck/issues/311

**Comment by rdipardo** [comment]
> See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4427

After some trial and error, I haven't been able to reproduce the crash, and I'm thinking now it really depends on a particular version of the COM system libraries. A user on the linked thread [specifically claims] the crash will occur "only on Window Server operating systems, not on Windows client OSes".

Maybe someone can try this experiment to test a new theory I have.

Get a compressor like [UPX](https://github.com/upx/upx/releases) and "pack" Zoom Disabler before running it [^1]. What's interesting is that the DLL's import table will *seem* much smaller after packing. `CoUninitialize` and friends will disappear.

Now, that's only because the imports get moved around to places where a static analyzer can't find them (one reason why compressed binaries are often suspected of hiding malware). But the apparent removal of the imports also has a real effect at runtime, as explained [here]:

> Multiple instances of a compressed EXE/DLL create multiple instances of the code in memory. . . . With uncompressed EXE/DLLs, code is only stored in memory once and is __*shared between instances*__.

It sounds like a packed DLL runs in greater isolation than a typical "shared" library. That might just be enough to prevent the fatal crossover of API calls into `combase.dll` that causes the crash.

[^1]: Delphi developers routinely pack their binaries because the compiler statically links in the whole runtime. Pascal libraries aren't common enough on end user devices to be taken for granted the way Microsoft's VC++ runtime can be.

[specifically claims]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4427#issuecomment-1379418392

[here]: https://jrsoftware.org/striprlc.php#execomp
